### ISSUE TITLE
Rspecのテストを追加する

### ISSUE THREAD

**Issue by takumiyamamoto** [Chino-s/travel_c#21]
## 経緯

#5 の続き

Rspecのコミットと不要なファイルが削除されたのでRapecのテストを追加する

## 要件

* `app/controllers/cities_controller.rb`についてのRspecを追加する
* テスト内容（例）
  * どんなViewが呼び出されるのかを確認する：`render_template`
  * どんな引数が設定されているのかを確認する：`instance_variable_get`

## その他

エビデンスについてはRspecの実行結果のログをのせること

この次のissueからは`models`や`controller`に変更があったら
その都度、Rspecを追加してエビデンスに実行結果を記載すること

**Comment by takumiyamamoto** [comment]
@Chino-s ざっくりだけどこんな感じかな？

```
describe XXXXXController do

  describe "GET 'edit'" do
    it "should returns http success" do
      get 'edit'
      response.should be_success
    end

    it "should assigns @user" do
      get 'edit'
      assigns[:user].should_not be_nil
    end
  end

end
```

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
describe CountriesController do
require "rspec/rails"
require "CountriesController"

  describe "GET 'show'" do
    it "should returns http success" do
      get 'show'
      response.should be_success
    end

    it "should assigns @id" do
      get 'show'
      assigns[:id].should_not be_nil
    end
  end
end
```

```
$ bundle exec rspec spec/controllers/countries_controller_spec.rb
bundler: failed to load command: rspec (/Users/sakura/.rbenv/versions/2.2.3/bin/rspec)
NameError: uninitialized constant CountriesController
  /Users/sakura/travel_c/spec/controllers/countries_controller_spec.rb:1:in `<top (required)>'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
  /Users/sakura/.rbenv/versions/2.2.3/bin/rspec:23:in `load'
  /Users/sakura/.rbenv/versions/2.2.3/bin/rspec:23:in `<top (required)>'
```

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
$ gem list rspec

*** LOCAL GEMS ***

rspec (3.4.0)
rspec-core (3.4.4, 2.14.8)
rspec-expectations (3.4.0, 2.14.5)
rspec-mocks (3.4.1, 2.14.6)
rspec-rails (2.14.2)
rspec-support (3.6.0, 3.4.1)

$ rails -v
Rails 3.2.22.5
```

**Comment by Chino-s** [comment]
上のエラーはバージョンの問題でしょうか？

**Comment by takumiyamamoto** [comment]
@Chino-s 以下が問題だね

`NameError: uninitialized constant CountriesController`

コントローラについてのrspecの書き方を検索した方がいいかもね

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
require 'rails_helper'

describe CountriesController do
  describe "GET 'show'" do
    it "should returns http success" do
      get 'show'
      response.should be_success
    end

    it "should assigns @id" do
      get 'show'
      assigns[:id].should_not be_nil
    end

  end
end

```

ネットで調べて見てこのように書いてあったんですが、

```
$ bundle exec rspec spec/controllers/countries_controller_spec.rb
bundler: failed to load command: rspec (/Users/sakura/.rbenv/versions/2.2.3/bin/rspec)
LoadError: cannot load such file -- CountriesController
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
  /Users/sakura/travel_c/spec/spec_helper.rb:4:in `<top (required)>'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/sakura/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
  /Users/sakura/.rbenv/versions/2.2.3/bin/rspec:23:in `load'
  /Users/sakura/.rbenv/versions/2.2.3/bin/rspec:23:in `<top (required)>'
```

となってしまいます。

**Comment by Chino-s** [comment]
@takumiyamamoto

解決しました。
手動でcountries_controller_spec.rb作成したのが原因のようです。

```

**Comment by Chino-s** [comment]
rspecのバーッジョンを合わせる

```
SakuraMBP:travel_c sakura$ gem list rspec

*** LOCAL GEMS ***

rspec (3.4.0)
rspec-core (3.4.4, 2.14.8)
rspec-expectations (3.4.0, 2.14.5)
rspec-mocks (3.4.1, 2.14.6)
rspec-rails (3.4.0, 2.14.2)
rspec-support (3.4.1)

```

**Comment by Chino-s** [comment]
```
$ bundle exec rspec spec/controllers/countries_controller_spec.rb
```

```
bundler: failed to load command: rspec (/Users/〇〇〇/.rbenv/versions/2.2.3/bin/rspec)
LoadError: cannot load such file -- rspec/rails
```

spec_helper.rb
```
require 'rspec/rails'
```
ファイルの中に追加

**Comment by Chino-s** [comment]
<img width="750" alt="2017-06-01 11 20 27" src="https://cloud.githubusercontent.com/assets/28725380/26662045/5db007ae-46bc-11e7-94ec-90f55393d6cc.png">

**Comment by takumiyamamoto** [comment]
@Chino-s  テストコマンドだけじゃなくてテストの実行結果もエビデンスとしてのせて欲しい

**Comment by takumiyamamoto** [comment]
@Chino-s 以下の内容についてざっくりレビューしたよ

```
describe  'GET #show' do

    it 'find data' do
      get :show
      expect(response).to render_template(:show)
    end

    context 'have data' do
      before :each do  #'add data in table'
        @countries1 = FactoryGirl.create(:country)
        @countries2 = FactoryGirl.create(:country)
      end
        it 'check find data' do
          get :show, id: country
          expect(assigns(:countries)).to eq countries
        end
    end

    context 'show data' do
      it 'show data template' do
        get :show, id: country
        expect(response).to render_template :show
      end
    end

  end
```

・renderでshowが使用されていることを確認しているので文言を変更

```
it 'find data' do
↓
it 'render :show' do
```

・モデルの配列を作っているわけではないので変数名を単数形にする

```
@countries1 = FactoryGirl.create(:country)
@countries2 = FactoryGirl.create(:country)
↓
@country_1 = FactoryGirl.create(:country)
@country_2 = FactoryGirl.create(:country)
```

・`country`はそもそも`id`の値ではないし`before`の中で作成された変数じゃないので呼べない

```
get :show, id: country
```

・`eq countries`の`countries`は`before`ないで作成sていないので呼べない
・`before`で作成して`it`ないで呼び出せるのは``@XXXX`の変数だけ

```
expect(assigns(:countries)).to eq countries
```

**Comment by Chino-s** [comment]
#21 
# countries_controllerのshowテスト実行結果

```
$ bundle exec rspec spec/controllers/countries_controller_spec.rb 

Randomized with seed 46169
.....

Finished in 0.1126 seconds (files took 4.67 seconds to load)
5 examples, 0 failures

Randomized with seed 46169
```

**Comment by takumiyamamoto** [comment]
@Chino-s `show`のテストについて`context`があるけど

この`context`って必要なのかな？？？

どういう時に'context'で分けた方がいいって昨日説明したのかを思い出してみて

**Comment by Chino-s** [comment]
@takumiyamamoto 

不要ですね。
indexの時は、特定の条件別（データがある場合とない場合）に分けて
テストを行っていましたが、

今回のshowの場合は、
条件は同じ（データがある場合のみ）内容なので不要ですね。

他のところは大丈夫でしょうか？

**Comment by Chino-s** [comment]
@takumiyamamoto 

# Search 
 countries_controller_spec.rb

```
describe  'GET #search' do

    let(:params) { { name: @countries1 } }
    before :each do  #'add data in table'
      get :search, params
      @countries1 = FactoryGirl.create(:country)
      @countries2 = FactoryGirl.create(:country)
    end

    it 'return params' do
      request
      expect(assigns[:countries]).to eq([@countries1, @countries2])
    end

  end
```
# テスト実行結果

```
$ bundle exec rspec spec/controllers/countries_controller_spec.rb 

Randomized with seed 45712
......

Finished in 0.1175 seconds (files took 3.43 seconds to load)
6 examples, 0 failures

Randomized with seed 45712
```

**Comment by Chino-s** [comment]
# countries_controller_spec.rb

```
require 'rails_helper'

RSpec.describe CountriesController, :type => :controller do

  describe  'GET #index' do

    it 'show view' do
      get :index
      expect(response).to render_template(:index)
    end

    context 'have data' do
      before :each do  #'add data in table'
        @countries1 = FactoryGirl.create(:country)
        @countries2 = FactoryGirl.create(:country)
      end
      it 'check order data' do
        get :index
        expect(assigns[:countries]).to eq([@countries1, @countries2])
      end
    end

    context 'no have data' do
      it 'countries is empty array' do
        get :index
        expect(assigns[:countries]).to eq([])
      end
    end

  end


  describe  'GET #show' do

    let(:request) { get :show, { id: @country1 } }
    before :each do  #'add data in table'
      @country1 = FactoryGirl.create(:country)
    end

      it 'check find data' do
        request
        expect(assigns[:country]).to eq @country1
      end

      it 'show data template' do
        request
        expect(response).to render_template :show
      end

  end


  describe  'GET #search' do

    let(:params) { { name: @countries1 } }
    before :each do  #'add data in table'
      get :search, params
      @countries1 = FactoryGirl.create(:country)
      @countries2 = FactoryGirl.create(:country)
    end

    it 'return params' do
      request
      expect(assigns[:countries]).to eq([@countries1, @countries2])
    end

  end

end
```

**Comment by takumiyamamoto** [comment]
@Chino-s 軽くレビューするね

### `show`について

インデントがおかしい
  * `context`を消しただけでそのあとにインデントを直してない

###  `search`について：

１、そもそも指示したテストになっていない
２つデータを入れて１つだけにマッチするテストを作るように指示したのに全部に一致してるよ・・・。

２、なんでここだけ、何のテンプレートを呼び出すのかについてのテストがないのかな？？
何か理由があればコメント欲しい

３、`@countries1`の変数名について
すでに違う場所で変数名については指摘しているので見つけて直して

### 共通：letの使用方法について

`let`と同じ階層で`before`を使用するのであれば`before`で統一する
`before`ではなく`let`で別だしするなら別だしにすると便利になるという理由が必要

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
describe  'GET #search' do

    before :each do  #'add data in table'
      @country1 = FactoryGirl.create(:country, name: "abc")
      @country2 = FactoryGirl.create(:country)
      get :search
    end

    it 'check find @country1' do
      get :search, { name: @country1.name}
      expect(assigns[:country]).to eq @country1
      #expect(@country1[:name]).to eq "abc"
    end

    it 'return params' do
      get :search
      expect(response).to render_template :index
    end

  end
```

```
Randomized with seed 40268
...F...

Failures:

  1) CountriesController GET #search check find @country1
     Failure/Error: expect(assigns[:country]).to eq @country1
     
       expected: #<Country id: 1, name: "abc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 07:27:48", updated_at: "2017-06-05 07:27:48", imagephoto: "aaa", googlemap: "123">
            got: nil
     
       (compared using ==)
     # ./spec/controllers/countries_controller_spec.rb:63:in `block (3 levels) in <top (required)>'

Finished in 0.19792 seconds (files took 4.6 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/controllers/countries_controller_spec.rb:61 # CountriesController GET #search check find @country1
```

**Comment by takumiyamamoto** [comment]
@Chino-s 以下の記述がたくさんあるのはなせ？？

```
get :search
```

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
describe  'GET #search' do

    before :each do  #'add data in table'
      @country1 = FactoryGirl.create(:country, name: "abc")
      @country2 = FactoryGirl.create(:country)
      get :search
    end

    it 'check find @country1' do
      get :index, search: { name: "abc"}
      expect(assigns[:country]).to eq @country1
      #expect(@country1[:name]).to eq "abc"
    end

    it 'return params' do
      get :index
      expect(response).to render_template :index
    end

  end
```

```
Randomized with seed 934
F......

Failures:

  1) CountriesController GET #search check find @country1
     Failure/Error: expect(assigns[:country]).to eq @country1
     
       expected: #<Country id: 1, name: "abc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 09:05:28", updated_at: "2017-06-05 09:05:28", imagephoto: "aaa", googlemap: "123">
            got: nil
     
       (compared using ==)
     # ./spec/controllers/countries_controller_spec.rb:63:in `block (3 levels) in <top (required)>'

Finished in 0.20007 seconds (files took 4.76 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/controllers/countries_controller_spec.rb:61 # CountriesController GET #search check find @country1
```

**Comment by takumiyamamoto** [comment]
@Chino-s 以下の記述を書くとそれはもう`def search`のテストじゃなくて`def index`のテスト

`get :index`

**Comment by Chino-s** [comment]
@takumiyamamoto 

http://qiita.com/hitomi_/items/09c3503f06a7a7575b38
上のサイトの
```
describe "params[:search]で検索条件があれば、それを返すこと" do
      it "コメント検索" do
        comment = "コメント"
        task = create(:task, comment: comment)
        get :index, search: {comment: comment}
        expect(assigns(:admins_tasks).last.comment).to eq comment
      end

      it "メモ検索" do
        memo = "メモ"
        task = create(:task, memo: memo)
        get :index, search: {memo: memo}
        expect(assigns(:admins_tasks).last.memo).to include memo
      end
    end

    it "renders ther :index template" do
      get :index
      expect(response).to render_template :index
    end
  end
```
この部分を参考にしたんですが、
違いましたか？

**Comment by Chino-s** [comment]
@takumiyamamoto 

assigns[:country]

ここの件なんですが、
```
  describe  'GET #index' do

    it 'response render :index' do
      get :index
      expect(response).to render_template :index
    end

    context 'have data' do
      before :each do  #'add data in table'
        @countries1 = FactoryGirl.create(:country)
        @countries2 = FactoryGirl.create(:country)
      end
      it 'check order data' do
        get :index
        expect(assigns[:countries]).to eq([@countries1, @countries2])
      end
    end

    context 'no have data' do
      it 'countries is empty array' do
        get :index
        expect(assigns[:countries]).to eq([])
      end
    end
```
```
  describe  'GET #show' do

    let(:request) { get :show, { id: @country1 } }
    before :each do  #'add data in table'
      @country1 = FactoryGirl.create(:country)
    end

    it 'check find data' do
      request
      expect(assigns[:country]).to eq @country1
    end

    it 'response render :show' do
      request
      expect(response).to render_template :show
    end

  end
```

この部分ではテストは通っているので、
@countryの値はあるはずです。

**Comment by takumiyamamoto** [comment]
@Chino-s `show`と`search`は全く異なるメソッドだから

それは`@country`がある証拠には全くならないよ

**Comment by Chino-s** [comment]
@takumiyamamoto 

@country2 = FactoryGirl.create(:country)
ここで@countryを作成してることにはならないんですか？

**Comment by takumiyamamoto** [comment]
@Chino-s 以下で確認できる値はコントローラで作成している値

```
assigns(:XXXXX)
```

```
[XXXController.rb]

def XXXX
  @hogehoge = `FFFFFF` 
end
```

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
  # 国ID検索
  def search
    @countries = Country.search(params[:q])
    render "index"
  end
```

ここで@countriesにしてるので、
```
  describe  'GET #search' do

    before :each do  #'add data in table'
      @countries1 = FactoryGirl.create(:countries, name: "abc")
      @countries2 = FactoryGirl.create(:countries)
    end

    it 'check find @country1' do
      get :index, search: { name: "abc"}
      expect(assigns[:countries]).to eq @countries1
      #expect(@country1[:name]).to eq "abc"
    end

    it 'return params' do
      get :index
      expect(response).to render_template :index
    end

  end
```


ってことですか？

**Comment by takumiyamamoto** [comment]
@Chino-s 

テンプレートがない時は以下の記述でやるのはあってるよ

```
get :index, search: {comment: comment}
```

上は`index`のあとに`search`へアクセスしてる


でも以下の記述だと`index`にアクセスした後の`response`を見るから`index`のテストにする

```
 it "renders ther :index template" do
      get :index
      expect(response).to render_template :index
    end
```

**Comment by Chino-s** [comment]
@takumiyamamoto 

```
    it 'return params' do
      get :index, search: { name: "abc"}
      expect(response).to render_template :index
    end
```

こういうことですか？

**Comment by Chino-s** [comment]
@takumiyamamoto 

@countriesの件なんですが、
実行したところ
```
1) CountriesController GET #search check find @country1
     Failure/Error: expect(assigns[:countries]).to eq @countries1
     
       expected: #<Country id: 1, name: "abc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 11:00:58", updated_at: "2017-06-05 11:00:58", imagephoto: "aaa", googlemap: "123">
            got: [#<Country id: 1, name: "abc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 11:00:58", updated_at: "2017-06-05 11:00:58", imagephoto: "aaa", googlemap: "123">, #<Country id: 2, name: "aabbcc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 11:00:58", updated_at: "2017-06-05 11:00:58", imagephoto: "aaa", googlemap: "123">]
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -#<Country id: 1, name: "abc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 11:00:58", updated_at: "2017-06-05 11:00:58", imagephoto: "aaa", googlemap: "123">
       +[#<Country id: 1, name: "abc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 11:00:58", updated_at: "2017-06-05 11:00:58", imagephoto: "aaa", googlemap: "123">, #<Country id: 2, name: "aabbcc", language: "abc", capital: "a", area_id: 1, popular_ranking: 4, created_at: "2017-06-05 11:00:58", updated_at: "2017-06-05 11:00:58", imagephoto: "aaa", googlemap: "123">]
```

と１、２両方の値を得てしまって
絞れていなかったです。

**Comment by takumiyamamoto** [comment]
@Chino-s 以下を実行した時の設定ってnameに何が初期値とわたるように設定した？？

```
FactoryGirl.create(:countries)
```

**Comment by Chino-s** [comment]
@takumiyamamoto
 
name "aabbcc"

これです。

**Comment by Chino-s** [comment]
countries_controller.rb

```
  # 国ID検索
  def search
    @countries = Country.search(params[:q])
    render "index"
  end
```

**Comment by Chino-s** [comment]
countries_controller_spec.rb

```
  describe  'GET #search' do

    before :each do  #'add data in table'
      @country1 = FactoryGirl.create(:country, name: "abc")
      @country2 = FactoryGirl.create(:country)
    end

    it 'response render :index' do
      get :search, q: @country1.name
      expect(response).to render_template :index
    end

    it 'when no params[:q], assigns[:countries] is all country' do
      get :search
      expect(assigns[:countries]).to eq [@country1, @country2]
    end

    it 'when have params[:q], assigns[:countries] search country' do
      get :search, q: @country1.name
      expect(assigns[:countries]).to eq [@country1]
      expect(assigns[:countries].first.name).to eq @country1.name
    end

  end
```
